name: CI/CD
on:
  push:
    branches:
      - main
jobs:
   build:
     name: Job_1
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@*      
       - name: Install Terraform 
         run: | 
           ${{env.COMMANDS}}
       - name: change the directory
         run: cd $(dirname terraform/main.tf)
       - name: Initialize Terraform 
         run: terraform init
       - name: Validate Terraform code 
         run: terraform validate 

